name: 'Modele Issue - DoD & Modifications'
description: "Formulaire de creation d'issue pour la gestion des DoD et des modifications apportees"
title: "[ISSUE] Titre de l'issue"
labels:
    - 'documentation'
    - 'enhancement'
body:
    - type: input
      id: objectif_principal
      attributes:
          label: 'Objectif Principal'
          description: 'Décrivez la finalité business/technique de cette issue'
          placeholder: "Exemple : Améliorer la gestion des erreurs dans l'API"
    - type: textarea
      id: modifications
      attributes:
          label: 'Modifications Apportées'
          description: "Détaillez les changements majeurs, l'architecture modifiée, les dépendances ajoutées/supprimées"
          placeholder: "- Ajout d'un middleware de gestion des erreurs\n- Refactoring du module X"
    - type: checkboxes
      id: dod_qualite
      attributes:
          label: 'DoD - Qualité'
          description: 'Les standards de code et les tests nécessaires'
          options:
              - label: 'Les standards de code sont respectés.'
              - label: 'Les tests nécessaires ont été exécutés.'
    - type: checkboxes
      id: dod_diffusion
      attributes:
          label: 'DoD - Diffusion'
          description: 'Communication et mise à jour des informations'
          options:
              - label: "L'information nécessaire a été communiquée au reste de l'équipe."
              - label: "Les radiateurs d'information correspondants ont été actualisés."
              - label: 'La documentation correspondante a été écrite ou actualisée.'
    - type: checkboxes
      id: dod_revision
      attributes:
          label: 'DoD - Révision'
          description: 'Vérification de la qualité interne et des démonstrations'
          options:
              - label: "La qualité interne se maintient ou s'améliore."
              - label: 'Le Product Owner a vu une démonstration.'
              - label: 'Une pré-démonstration (démonstration à blanc) a été réalisée.'
              - label: 'La démonstration correspondante a été préparée.'
    - type: checkboxes
      id: dod_environnements
      attributes:
          label: 'DoD - Environnements'
          description: 'Stockage du code et du produit complet'
          options:
              - label: 'Le code impliqué est stocké dans un contrôleur de source.'
              - label: 'Le produit complet est stocké dans un contrôleur de source.'
